_target_: src.models.SpatialClip  # Your main model class
image_dim: 512
text_dim: 512
obj_dim: 256
depth_dim: 128
hidden_dim: 1024
out_dim: 512

active_encoders:
  use_text: false   # Change to true for later experiments
  use_obj: true
  use_depth: false