_target_: scripts.datamodules.WaymoDataModule
batch_size: 64
num_workers: 4
data_dir: "data/waymo/raw"
image_size: 224
dataset_cfg:
  use_text: ${model.active_encoders.use_text}   # Links to your model config
  use_depth: ${model.active_encoders.use_depth}
  use_obj: ${model.active_encoders.use_obj}